[package]
name = "clicketyclack"
version = "0.1.0"
authors = ["Magnus Bergmark <me@mange.dev>"]
license = "MIT"
edition = "2021"
build = "build.rs"

[dependencies]
rodio = "0.13.0"
structopt = "0.3.21"

[target.'cfg(unix)'.dependencies]
libc = "0.2.82"

[build-dependencies]
cmake = "0.1.31"
