#!/bin/sh
#
# Regenerate `src/resources.rs`.
#

sanitize_identifier() {
  tr -cd 'a-z_'
}

(
  echo "// THIS FILE HAS BEEN GENERATED BY generate_resources.sh"
  echo "// DO NOT EDIT IT BUT INSTEAD CHANGE THE GENERATOR"
  echo ""

  for modelpath in ./resources/*; do
    if ! [ -d "$modelpath" ]; then
      continue
    fi

    modelident="$(basename "${modelpath}" | sanitize_identifier)"

    for direction in down up; do
      echo "pub fn load_${modelident}_${direction}() -> Vec<&'static [u8]> {"
      echo "    vec!["
      for file in "${modelpath}/${direction}"*.wav; do
        # Add initial dot so "./resources…" turns into "../resources…". This fixes
        # the path when the generated file is placed under src/ instead of the
        # project root.
        echo "        include_bytes!(\".${file}\"),"
      done
      echo "    ]"
      echo "}"
      echo ""
    done
  done
) | rustfmt | tee src/resources.rs


echo "(Written to src/resources.rs)" >&2
