// THIS FILE HAS BEEN GENERATED BY generate_resources.sh
// DO NOT EDIT IT BUT INSTEAD CHANGE THE GENERATOR

pub fn load_kailh_white_down() -> Vec<&'static [u8]> {
    vec![
        include_bytes!("../resources/kailh_white/down1.wav"),
        include_bytes!("../resources/kailh_white/down2.wav"),
        include_bytes!("../resources/kailh_white/down3.wav"),
        include_bytes!("../resources/kailh_white/down4.wav"),
        include_bytes!("../resources/kailh_white/down5.wav"),
    ]
}

pub fn load_kailh_white_up() -> Vec<&'static [u8]> {
    vec![
        include_bytes!("../resources/kailh_white/up1.wav"),
        include_bytes!("../resources/kailh_white/up2.wav"),
        include_bytes!("../resources/kailh_white/up3.wav"),
        include_bytes!("../resources/kailh_white/up4.wav"),
        include_bytes!("../resources/kailh_white/up5.wav"),
    ]
}
